[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash -c '/app/generate-keys-if-missing.sh && node server.js'"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "zklogin-prover"
port = 4000

[[volumes]]
name = "keys-storage"
mountPath = "/app/keys"