[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = ""
watchPatterns = ["server.js", "circuits/**", "package.json"]

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "zklogin-prover"
port = 4000